apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  containers:
    - name: nginx
      image: sameersbn/owncloud:10.0.10-0
      args: ["app:nginx"]
      env:
        - name: OWNCLOUD_URL
          value: http://cloud.example.com

        - name: OWNCLOUD_PHP_FPM_HOST
          value: owncloud
        - name: OWNCLOUD_PHP_FPM_PORT
          value: "9000"

      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: owncloud
  labels:
    name: owncloud
spec:
  ports:
    - name: php-fpm
      port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    name: owncloud
---
apiVersion: v1
kind: Pod
metadata:
  name: owncloud
  labels:
    name: owncloud
spec:
  containers:
    - name: owncloud
      image: sameersbn/owncloud:10.0.10-0
      args: ["app:owncloud"]
      env:
        - name: TZ
          value: Asia/Kolkata
        - name: DEBUG
          value: "false"

        - name: OWNCLOUD_URL
          value: http://cloud.example.com

        - name: OWNCLOUD_ADMIN_USER
          value: admin
        - name: OWNCLOUD_ADMIN_PASSWORD
          value: password

        - name: OWNCLOUD_UPLOAD_MAX_FILESIZE
          value: 4G
        - name: OWNCLOUD_MAX_FILE_UPLOADS
          value: "20"

        - name: DB_TYPE
          value: pgsql
        - name: DB_HOST
          value: postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: owncloud
        - name: DB_PASS
          value: password
        - name: DB_NAME
          value: owncloud_db

      ports:
        - name: php-fpm
          containerPort: 9000
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/owncloud
          name: data
      livenessProbe:
        tcpSocket:
          port: 9000
        initialDelaySeconds: 5
        timeoutSeconds: 1
  volumes:
    - name: data
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    name: postgresql
---
apiVersion: v1
kind: Pod
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  containers:
    - name: postgresql
      image: sameersbn/postgresql:9.6-4
      env:
        - name: DB_USER
          value: owncloud
        - name: DB_PASS
          value: password
        - name: DB_NAME
          value: owncloud_db
      ports:
        - containerPort: 5432
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/postgresql
          name: data
      livenessProbe:
        tcpSocket:
          port: 5432
        initialDelaySeconds: 30
        timeoutSeconds: 5
  volumes:
    - name: data
      emptyDir: {}