---
apiVersion: v1
kind: Service
metadata:
  name: myhero-data
  labels:
    app: myhero
    tier: data
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: myhero
    tier: data
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myhero-data
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myhero
        tier: data
    spec:
      containers:
      - name: myhero-data
        image: hpreston/myhero_data:latest
        livenessProbe:
          httpGet:
            path: /hero_list
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /hero_list
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
          - name: myhero_data_key
            value: SecureData
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 64M
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: myhero-mosca
  labels:
    app: myhero
    tier: mosca
spec:
  ports:
  - port: 1883
    targetPort: 1883
  selector:
    app: myhero
    tier: mosca
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myhero-mosca
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myhero
        tier: mosca
    spec:
      containers:
      - name: myhero-mosca
        image: matteocollina/mosca:latest
        livenessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 1883
          name: mqtt
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 64M
      restartPolicy: Always
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myhero-ernst
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myhero
        tier: ernst
    spec:
      containers:
      - name: myhero-ernst
        image: hpreston/myhero_ernst:latest
        env:
          - name: myhero_mqtt_host
            value: myhero-mosca
          - name: myhero_mqtt_port
            value: "1883"
          - name: myhero_data_srv
            value: myhero-data
          - name: myhero_data_key
            value: SecureData
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 32M
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: myhero-app
  labels:
    app: myhero
    tier: app
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: myhero
    tier: app
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myhero-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: myhero
        tier: app
    spec:
      containers:
      - name: myhero-app
        image: hpreston/myhero_app:latest
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
          - name: myhero_mqtt_host
            value: myhero-mosca
          - name: myhero_mqtt_port
            value: "1883"
          - name: myhero_app_mode
            value: queue
          - name: myhero_data_srv
            value: myhero-data
          - name: myhero_data_key
            value: SecureData
          - name: myhero_app_key
            value: SecureApp
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 48M
      restartPolicy: Always












